name: workflow trigger
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with: 
          name: ${{ env.ARTIFACT_NAME }}
          path: .
